# Generated by Django 2.2.6 on 2020-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200615_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='imageName',
        ),
        migrations.AddField(
            model_name='news',
            name='imageUrl',
            field=models.TextField(default=' '),
        ),
    ]
