# Generated by Django 2.2.6 on 2020-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ocategory_id',
            field=models.IntegerField(default=0),
        ),
    ]
