# Generated by Django 2.2.6 on 2020-06-17 14:11

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=martor.models.MartorField(),
        ),
    ]
