# Generated by Django 2.2.6 on 2020-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200611_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.TextField(default=' '),
        ),
    ]
