# Generated by Django 2.2.6 on 2020-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200613_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_nane',
            field=models.TextField(default=' '),
        ),
    ]
