# Generated by Django 2.2.6 on 2020-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200613_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='main',
            name='tell',
            field=models.TextField(default=' '),
        ),
    ]
