# Generated by Django 2.2.6 on 2020-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200613_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(max_length=30),
        ),
    ]
